version: '3.8'

services:
  eduba:
    image: ghcr.io/randdofficial/eduba-board:latest
    container_name: eduba-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./sqlite.db:/app/sqlite.db
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production