services:
  eduba:
    image: ghcr.io/randdofficial/eduba-board:latest
    container_name: eduba-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ALLOW_REGISTRATION=true
      - BACKUP_INTERVAL_HOURS=48
      - MAX_BACKUPS=5
    volumes:
      - ./data:/app/data